# include("testcharts.jl")
# include("testrbm.jl")
# include("testmomentum.jl")
# include("testaccel.jl")
# include("testnets.jl")
# include("testweightdecay.jl")
# include("testgaussianrbm.jl")
include("testdropout.jl")
